version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: chef/chefdk # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: chef-client --local-mode --override-runlist hello-chef
  test:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: chef/chefdk # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: inspec exec cookbooks/hello-chef/test/integration/default/default_test.rb
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
